[build]
    command = "npm run dev"
    publish = "/pages"
    base = "/"

[[redirects]]
    from ="/"
    to = "/pages"
    status = 200

[[plugins]]
    package = "netlify-plugin-cache-nextjs"
    # These options will cache the build directory at `${NETLIFY_BASE}/pages/.next-build`
    [plugins.inputs]   
    build_dir_path = "pages"
    
